services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: "${SERVER_NAME:-http://localhost:8080}"
      CADDY_GLOBAL_OPTIONS: "auto_https off"
    tty: true

volumes:
  caddy_data:
  caddy_config:
